onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_wishbone/simdone
add wave -noupdate /tb_top_wishbone/Clk
add wave -noupdate /tb_top_wishbone/Rst
add wave -noupdate /tb_top_wishbone/TimeoutAck_Detected
add wave -noupdate /tb_top_wishbone/TimeoutAck_Rec_Clear
add wave -noupdate /tb_top_wishbone/executing_line
add wave -noupdate /tb_top_wishbone/executing_file
add wave -noupdate /tb_top_wishbone/marker
add wave -noupdate /tb_top_wishbone/signals_in
add wave -noupdate /tb_top_wishbone/signals_out
add wave -noupdate /tb_top_wishbone/bus_down
add wave -noupdate /tb_top_wishbone/bus_up
add wave -noupdate /tb_top_wishbone/EventCatcherIfcWishboneDown
add wave -noupdate /tb_top_wishbone/EventCatcherIfcWishboneUp
add wave -noupdate /tb_top_wishbone/EventCatcherIfcEventCatcherBlkDown
add wave -noupdate /tb_top_wishbone/EventCatcherIfcEventCatcherBlkUp
add wave -noupdate /tb_top_wishbone/EventCatcherIfcTrace
add wave -noupdate /tb_top_wishbone/EventOut
add wave -noupdate /tb_top_wishbone/PreviousEventOut0
add wave -noupdate /tb_top_wishbone/EventCatch
add wave -noupdate /tb_top_wishbone/EventPuls
add wave -noupdate /tb_top_wishbone/EventPuls0
add wave -noupdate /tb_top_wishbone/EventPuls1
add wave -noupdate /tb_top_wishbone/EventPuls2
add wave -noupdate /tb_top_wishbone/EventPuls3
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/Clk
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/Rst
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/WishboneDown
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/WishboneUp
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/Trace
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/EventCatcherBlkDown
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/EventCatcherBlkUp
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/BlockMatch
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/UnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/TimeoutAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/PreWishboneUp
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/EventCatcherBlkDatOut
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/EventCatcherBlkAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/EventCatcherBlkMatch
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/Clk
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/Rst
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/Cyc
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/Match
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/UnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/TimeoutAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/CycDelay
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/PreUnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/PreTimeoutAck
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherIfcBusMonitor/TimeoutCounter
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Clk
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Rst
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Adr
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Sel
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/DatIn
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/We
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Stb
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Cyc
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/DatOut
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Ack
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Match
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/Mask
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/CatchToBeRead
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/CatchWritten
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WTransPulseEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/OverrunToBeRead
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/OverrunWritten
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WTransPulseEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreDatOut
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreDatOutEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreReadAckEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/ReadDiffEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreWriteAckEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WriteDiffEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WRegMask
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchReadEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchWriteEventMaskReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreDatOutEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreReadAckEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/ReadDiffEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreWriteAckEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WriteDiffEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchReadEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchWriteEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreDatOutEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreReadAckEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/ReadDiffEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreWriteAckEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/WriteDiffEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchReadEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcherIfcWishbone/i_EventCatcherBlk_EventCatcherIfc/PreMatchWriteEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcher/Clk
add wave -noupdate /tb_top_wishbone/i_EventCatcher/Rst
add wave -noupdate /tb_top_wishbone/i_EventCatcher/EventPuls
add wave -noupdate /tb_top_wishbone/i_EventCatcher/EventCatch
add wave -noupdate /tb_top_wishbone/i_EventCatcher/Mask
add wave -noupdate /tb_top_wishbone/i_EventCatcher/CatchWritten
add wave -noupdate /tb_top_wishbone/i_EventCatcher/WTransPulseEventCatchReg
add wave -noupdate /tb_top_wishbone/i_EventCatcher/CatchToBeRead
add wave -noupdate /tb_top_wishbone/i_EventCatcher/OverrunWritten
add wave -noupdate /tb_top_wishbone/i_EventCatcher/WTransPulseEventOverrunReg
add wave -noupdate /tb_top_wishbone/i_EventCatcher/OverrunToBeRead
add wave -noupdate /tb_top_wishbone/i_EventCatcher/Catch
add wave -noupdate /tb_top_wishbone/i_EventCatcher/Overrun
add wave -noupdate /tb_top_wishbone/i_tb_simstm/clk
add wave -noupdate /tb_top_wishbone/i_tb_simstm/rst
add wave -noupdate /tb_top_wishbone/i_tb_simstm/simdone
add wave -noupdate /tb_top_wishbone/i_tb_simstm/executing_line
add wave -noupdate /tb_top_wishbone/i_tb_simstm/executing_file
add wave -noupdate /tb_top_wishbone/i_tb_simstm/marker
add wave -noupdate /tb_top_wishbone/i_tb_simstm/signals_out
add wave -noupdate /tb_top_wishbone/i_tb_simstm/signals_in
add wave -noupdate /tb_top_wishbone/i_tb_simstm/bus_down
add wave -noupdate /tb_top_wishbone/i_tb_simstm/bus_up
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1784228 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1784050 ps} {1785050 ps}
