onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_wishbone/simdone
add wave -noupdate /tb_top_wishbone/Clk
add wave -noupdate /tb_top_wishbone/Rst
add wave -noupdate /tb_top_wishbone/TimeoutAck_Detected
add wave -noupdate /tb_top_wishbone/TimeoutAck_Rec_Clear
add wave -noupdate /tb_top_wishbone/executing_line0
add wave -noupdate /tb_top_wishbone/executing_file0
add wave -noupdate /tb_top_wishbone/marker0
add wave -noupdate /tb_top_wishbone/signals_in0
add wave -noupdate /tb_top_wishbone/signals_out0
add wave -noupdate /tb_top_wishbone/bus_down0
add wave -noupdate /tb_top_wishbone/bus_up0
add wave -noupdate /tb_top_wishbone/executing_line1
add wave -noupdate /tb_top_wishbone/executing_file1
add wave -noupdate /tb_top_wishbone/marker1
add wave -noupdate /tb_top_wishbone/signals_in1
add wave -noupdate /tb_top_wishbone/signals_out1
add wave -noupdate /tb_top_wishbone/bus_down1
add wave -noupdate /tb_top_wishbone/bus_up1
add wave -noupdate /tb_top_wishbone/InterruptCollectorIfcWishboneDown
add wave -noupdate /tb_top_wishbone/InterruptCollectorIfcWishboneUp
add wave -noupdate /tb_top_wishbone/InterruptCollectorIfcInterruptCollectorBlkDown
add wave -noupdate /tb_top_wishbone/InterruptCollectorIfcInterruptCollectorBlkUp
add wave -noupdate /tb_top_wishbone/InterruptCollectorIfcTrace
add wave -noupdate /tb_top_wishbone/InterruptGeneratorIfcWishboneDown
add wave -noupdate /tb_top_wishbone/InterruptGeneratorIfcWishboneUp
add wave -noupdate /tb_top_wishbone/InterruptGeneratorIfcTrace
add wave -noupdate /tb_top_wishbone/InterruptGeneratorIfcInterruptGeneratorBlkDown
add wave -noupdate /tb_top_wishbone/InterruptGeneratorIfcInterruptGeneratorBlkUp
add wave -noupdate /tb_top_wishbone/BusDividerIfcWishboneDown
add wave -noupdate /tb_top_wishbone/BusDividerIfcWishboneUp
add wave -noupdate /tb_top_wishbone/BusDividerIfcTrace
add wave -noupdate /tb_top_wishbone/BusDividerIfcBusDividerBlkDown
add wave -noupdate /tb_top_wishbone/BusDividerIfcBusDividerBlkUp
add wave -noupdate /tb_top_wishbone/Cyc
add wave -noupdate /tb_top_wishbone/Adr
add wave -noupdate /tb_top_wishbone/Sel
add wave -noupdate /tb_top_wishbone/We
add wave -noupdate /tb_top_wishbone/Stb
add wave -noupdate /tb_top_wishbone/DatIn
add wave -noupdate /tb_top_wishbone/DatOut
add wave -noupdate /tb_top_wishbone/Ack
add wave -noupdate /tb_top_wishbone/JoinCyc
add wave -noupdate /tb_top_wishbone/JoinAdr
add wave -noupdate /tb_top_wishbone/JoinSel
add wave -noupdate /tb_top_wishbone/JoinWe
add wave -noupdate /tb_top_wishbone/JoinStb
add wave -noupdate /tb_top_wishbone/JoinDatOut
add wave -noupdate /tb_top_wishbone/JoinDatIn
add wave -noupdate /tb_top_wishbone/JoinAck
add wave -noupdate /tb_top_wishbone/GeneratedInterrupt
add wave -noupdate /tb_top_wishbone/GeneratorFailure
add wave -noupdate /tb_top_wishbone/InterruptToCpu
add wave -noupdate /tb_top_wishbone/ChannelOperation
add wave -noupdate /tb_top_wishbone/ChannelStatus
add wave -noupdate /tb_top_wishbone/ChargedCount
add wave -noupdate /tb_top_wishbone/ActualCount
add wave -noupdate /tb_top_wishbone/FailureCount
add wave -noupdate /tb_top_wishbone/Interval
add wave -noupdate /tb_top_wishbone/ReferenceCount
add wave -noupdate /tb_top_wishbone/WRegPulseReferenceCount
add wave -noupdate /tb_top_wishbone/Mask
add wave -noupdate /tb_top_wishbone/RequestWritten
add wave -noupdate /tb_top_wishbone/ServiceWritten
add wave -noupdate /tb_top_wishbone/RequestToBeRead
add wave -noupdate /tb_top_wishbone/ServiceToBeRead
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Clk
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Rst
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Cyc
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Adr
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Sel
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/We
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Stb
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/DatIn
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/DatOut
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/Ack
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinCyc
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinAdr
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinSel
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinWe
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinStb
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinDatOut
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinDatIn
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/JoinAck
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/MissCountTable
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/SelectedBus
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/State
add wave -noupdate /tb_top_wishbone/i_BusJoinWishbone/StateNumbered
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/Clk
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/Rst
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/WishboneDown
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/WishboneUp
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/Trace
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BusDividerBlkDown
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BusDividerBlkUp
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BlockMatch
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/UnoccupiedAck
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/TimeoutAck
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/PreWishboneUp
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BusDividerBlkDatOut
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BusDividerBlkAck
add wave -noupdate /tb_top_wishbone/i_BusDividerIfcWishbone/BusDividerBlkMatch
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/Clk
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/Rst
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/InterruptIn
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/InterruptOut
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/Mask
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/RequestWritten
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/WTransPulseInterruptRequestReg
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/RequestToBeRead
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/ServiceWritten
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/WTransPulseInterruptServiceReg
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/ServiceToBeRead
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/Request
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/Service
add wave -noupdate /tb_top_wishbone/i_InterruptCollector/MaskedRequest
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/Clk
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/Rst
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/InterruptOut
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/FailureOut
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/ChannelOperation
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/ChannelStatus
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/ChargedCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/ActualCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/FailureCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/Interval
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/ReferenceCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/WRegPulseReferenceCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/IntervalCount
add wave -noupdate /tb_top_wishbone/i_InterruptGenerator/IntervalEnable
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {6887881108 ps} {6887916784 ps}
