/* Copyright (C) 2024 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler v0.0.0-0000000
   C Extension for HxS 1.0.24-85d98215
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _InterruptCollectorIfc_H
#define _InterruptCollectorIfc_H

/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define InterruptCollectorIfcAddressBusWidth 4
#define InterruptCollectorIfcDataBusWidth 32

#define InterruptCollectorBlkAddress 0x0
#define InterruptCollectorBlkSize 0xC

#define InterruptMaskRegAddress (0x0 + InterruptCollectorBlkAddress)
#define InterruptMaskRegWidth 32

#define Mask3Mask 0x00000008
#define Mask3Position 3
#define Mask3Width 1
#define Mask3_InterruptDisabledMVal 0x00000000
#define Mask3_InterruptEnabledMVal 0x00000008
#define Mask3BusResetMRstVal 0x00000000

#define Mask2Mask 0x00000004
#define Mask2Position 2
#define Mask2Width 1
#define Mask2_InterruptDisabledMVal 0x00000000
#define Mask2_InterruptEnabledMVal 0x00000004
#define Mask2BusResetMRstVal 0x00000000

#define Mask1Mask 0x00000002
#define Mask1Position 1
#define Mask1Width 1
#define Mask1_InterruptDisabledMVal 0x00000000
#define Mask1_InterruptEnabledMVal 0x00000002
#define Mask1BusResetMRstVal 0x00000000

#define Mask0Mask 0x00000001
#define Mask0Position 0
#define Mask0Width 1
#define Mask0_InterruptDisabledMVal 0x00000000
#define Mask0_InterruptEnabledMVal 0x00000001
#define Mask0BusResetMRstVal 0x00000000

#define InterruptRequestRegAddress (0x4 + InterruptCollectorBlkAddress)
#define InterruptRequestRegWidth 32

#define Request3Mask 0x00000008
#define Request3Position 3
#define Request3Width 1
#define Request3_NotPendingMVal 0x00000000
#define Request3_PendingMVal 0x00000008
#define Request3_NotConfirmedMVal 0x00000000
#define Request3_ConfirmedMVal 0x00000008
#define Request3_AsyncMRstVal 0x00000000

#define Request2Mask 0x00000004
#define Request2Position 2
#define Request2Width 1
#define Request2_NotPendingMVal 0x00000000
#define Request2_PendingMVal 0x00000004
#define Request2_NotConfirmedMVal 0x00000000
#define Request2_ConfirmedMVal 0x00000004
#define Request2_AsyncMRstVal 0x00000000

#define Request1Mask 0x00000002
#define Request1Position 1
#define Request1Width 1
#define Request1_NotPendingMVal 0x00000000
#define Request1_PendingMVal 0x00000002
#define Request1_NotConfirmedMVal 0x00000000
#define Request1_ConfirmedMVal 0x00000002
#define Request1_AsyncMRstVal 0x00000000

#define Request0Mask 0x00000001
#define Request0Position 0
#define Request0Width 1
#define Request0_NotPendingMVal 0x00000000
#define Request0_PendingMVal 0x00000001
#define Request0_NotConfirmedMVal 0x00000000
#define Request0_ConfirmedMVal 0x00000001
#define Request0_AsyncMRstVal 0x00000000

#define InterruptServiceRegAddress (0x8 + InterruptCollectorBlkAddress)
#define InterruptServiceRegWidth 32

#define Service3Mask 0x00000008
#define Service3Position 3
#define Service3Width 1
#define Service3_EndedMVal 0x00000000
#define Service3_InProcessMVal 0x00000008
#define Service3_NotConfirmedMVal 0x00000000
#define Service3_ConfirmedMVal 0x00000008
#define Service3_AsyncMRstVal 0x00000000

#define Service2Mask 0x00000004
#define Service2Position 2
#define Service2Width 1
#define Service2_EndedMVal 0x00000000
#define Service2_InProcessMVal 0x00000004
#define Service2_NotConfirmedMVal 0x00000000
#define Service2_ConfirmedMVal 0x00000004
#define Service2_AsyncMRstVal 0x00000000

#define Service1Mask 0x00000002
#define Service1Position 1
#define Service1Width 1
#define Service1_EndedMVal 0x00000000
#define Service1_InProcessMVal 0x00000002
#define Service1_NotConfirmedMVal 0x00000000
#define Service1_ConfirmedMVal 0x00000002
#define Service1_AsyncMRstVal 0x00000000

#define Service0Mask 0x00000001
#define Service0Position 0
#define Service0Width 1
#define Service0_EndedMVal 0x00000000
#define Service0_InProcessMVal 0x00000001
#define Service0_NotConfirmedMVal 0x00000000
#define Service0_ConfirmedMVal 0x00000001
#define Service0_AsyncMRstVal 0x00000000

#endif
